### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by yuyuyuyuuu** [Kiprey/CDG-ConstructionAlgorithm#1]
请问您使用的SVF与LLVM版本是多少呢，我在使用最新的SVF时程序编译出错，有一些函数对应不到，请问这个问题该怎么解决呢。
期待您的回答。

**Comment by Kiprey** [comment]
这个项目有一段时间了..... 印象有点模糊
LLVM 大概是10-12 版本之间
SVF 是 **一年前**（2021/2） 的最新版，或许你可以到[这个页面](https://github.com/SVF-tools/SVF/commits/master?after=3ac7d33938ae1528a4930edc1ff854248b389aff+635&branch=master)下获取一个 commit id，然后 checkout 过去再试试。

**Comment by yuyuyuyuuu** [comment]
好的非常感谢。

**Comment by yuyuyuyuuu** [comment]
`Scanning dependencies of target cdg
[ 16%] Building CXX object src/CMakeFiles/cdg.dir/CDG.cpp.o
[ 33%] Building CXX object src/CMakeFiles/cdg.dir/CDGBuilder.cpp.o
In file included from /data/Study/CDG-ConstructionAlgorithm/include/CDGBuilder.h:8,
                 from /data/Study/CDG-ConstructionAlgorithm/src/CDGBuilder.cpp:4:
/data/Study/CDG-ConstructionAlgorithm/include/CDG.h:89:28: warning: inline function 'ControlCDGNode* ControlDependenceGraph::addControlCDGNode(const BasicBlock*)' used but never defined
   89 |     inline ControlCDGNode *addControlCDGNode(const BasicBlock *nbb);
      |                            ^~~~~~~~~~~~~~~~~
/data/Study/CDG-ConstructionAlgorithm/include/CDG.h:102:21: warning: inline function 'CDGNode* ControlDependenceGraph::getCDGNode(SVF::NodeID)' used but never defined
  102 |     inline CDGNode *getCDGNode(NodeID id);
      |                     ^~~~~~~~~~
[ 50%] Building CXX object src/CMakeFiles/cdg.dir/CDmap.cpp.o
[ 66%] Building CXX object src/CMakeFiles/cdg.dir/findA2BInFunc.cpp.o
[ 83%] Building CXX object src/CMakeFiles/cdg.dir/main.cpp.o
[100%] Linking CXX executable ../bin/cdg
/usr/bin/ld: CMakeFiles/cdg.dir/CDGBuilder.cpp.o: in function `CDGBuilder::addInterCDGEdge(ControlDependenceNode*, ControlDependenceNode*)':
CDGBuilder.cpp:(.text+0xd): undefined reference to `ControlDependenceGraph::addCDGEdge(ControlDependenceNode*, ControlDependenceNode*, int)'
/usr/bin/ld: CMakeFiles/cdg.dir/CDGBuilder.cpp.o: in function `CDGBuilder::getOrAddControlCDGNode(llvm::BasicBlock const*)':
CDGBuilder.cpp:(.text+0x49): undefined reference to `ControlDependenceGraph::getCDGNode(unsigned int)'
/usr/bin/ld: CDGBuilder.cpp:(.text+0x5d): undefined reference to `ControlDependenceGraph::addControlCDGNode(llvm::BasicBlock const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/cdg.dir/build.make:181: bin/cdg] Error 1
make[1]: *** [CMakeFiles/Makefile2:178: src/CMakeFiles/cdg.dir/all] Error 2
make: *** [Makefile:84: all] Error 2`
您好打扰了，在构建过程中编译通过了，但是在链接过程中提示找不到定义的方法，请问这个是链接顺序导致的吗，您在开发过程中遇到过这个问题吗？

**Comment by Kiprey** [comment]
抱歉，这个我没有遇到过......
我先前遇到的链接错误是因为 clang 版本和 LLVM 版本不一致所造成的，但是这个看上去不太像是这个问题.....

**Comment by yuyuyuyuuu** [comment]
好的感谢博主，问题解决了，是对于inline的解释标准过高导致找不到定义，需要使用传统模式进行编译或者取消inline。

**Comment by Kiprey** [comment]
:thumbsup:
